
# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle这个工作流将用Gradle构建一个Java项目#更多信息请参见：https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Pull Request Builds   名称：Pull Request Builds

on: [pull_request]   在(pull_request):

jobs:   工作:
  Build:   构建:

    runs-on: ubuntu-latest   上运行:ubuntu-latest

    steps:   步骤:
    - uses: actions/checkout@v4-使用：actions/checkout@v4
    - name: Set up JDK 25   —name：安装JDK 25
      uses: actions/setup-java@v4用途:行动/ setup-java@v4
      with:   :
        distribution: 'temurin'
        java-version: 25   java版本:25
        cache: 'gradle'   藏起来‘gradle’。
    - name: Grant execute permission to gradlew—name：授予gradlew执行权限
      run: chmod +x gradlew   执行命令chmod x gradlew
    - name: Build and run Gametest with Gradle- name：用Gradle构建并运行Gametest
      run: ./gradlew build runGametest抢购:./gradlew构建runGametest
    - uses: actions/upload-artifact@v4-使用：actions/upload-artifact@v4
      with:   :
        name: "Compiled artifacts for Pull Request #${{github.event.number}}"#${{github.event.number}}"；
        path: build/libs   路径:建立/ libs
    - uses: actions/upload-artifact@v4-使用：actions/upload-artifact@v4
      if: always()   如果:总是()
      with:   :
        name: gametest-results   名称:gametest-results
        path: build/junit.xml   路径:建立/ junit.xml
